# This is a basic workflow to help you get started with Actions

name: Docker Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      - "!dockerfile/**"
      - "!deployment/**"
      - "!charts/**"
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ghcr.io/micya
  IMAGE_NAME: webapp
  IMAGE_TAG: linux
  DOCKERFILE: dockerfile/linux.dockerfile

  GHCR_PAT: ${{ secrets.GHCR_PAT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build docker image
      - name: Docker build
        run: |
          IMAGE_ID=$IMAGE_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "Building image: $IMAGE_ID"
          docker build -f $DOCKERFILE -t $IMAGE_ID .
          
      - name: GitHub container registry login
        run: |
          echo "Logging in to container registry"
          echo $GHCR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          
      - name: Docker push
        run: |
          IMAGE_ID=$IMAGE_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "Pushing image: $IMAGE_ID"
          docker push $IMAGE_ID
